### ISSUE TITLE
selectn cannot be used directly from bower

### ISSUE THREAD

**Issue by ChenRoth** [wilmoore/selectn.js#33] opened 2016-06-23 05:46 UTC
the bower module doesn't cover the dependency on `require`, so it cannot be used directly in the browser

**Comment by wilmoore** [comment] 2016-06-30 19:50
Hi @ChenRoth,

What problem are you having specifically? Have you tried using `https://npmcdn.com/selectn/selectn.min.js`?

**Comment by wilmoore** [comment] 2016-07-14 04:58
Thanks for the report. I am currently unable to reproduce given the amount of info provided, thus, I am going to close this for now; however, feel free to re-open if you have more info to provide.

Thanks again.

**Closed by wilmoore** 2016-07-14 04:58 UTC
